enyo.depends(
	"Flyweight.js",
	"RowServer.js",
	"StateManager.js",
	"VirtualScroller.js",
	"Buffer.js",
	"DisplayBuffer.js",
	"DomBuffer.js",
	"BufferedScroller.js",
	"ScrollingList.js",
	"VirtualList.js"
);