enyo.depends(
	"langTest.js",
	"KindTest.js",
	"JsonTest.js",
	"AsyncTest.js",
	"AjaxTest.js",
	"ComponentDispatchTest.js",
	"ComponentHandlersTest.js",
	"ControlPropsTest.js",
	"DecodePackagePathTest.js"
);
