enyo.depends(
	"log.js",
	"lang.js",
	"job.js",
	"macroize.js",
	"animation.js",
	"Oop.js",
  "Binding.js",
	"Object.js",
	"Component.js",
	"UiComponent.js",
	"Layout.js",
	"Signals.js",
	"Router.js",
	"Controller.js",
	"AppController.js",
	"ArrayController.js",
	"Extension.js"
);
