enyo.depends(
	"BaseLayout.js",
	"NoDom.js",
	"Image.js",
	"Input.js",
	"Select.js",
	"Group.js",
	"GroupItem.js",
	"ToolDecorator.js",
	"Button.js",
	"Checkbox.js",
	"Repeater.js",
	"DragAvatar.js",
	"ui.css"
);