enyo.depends(
	"touch.js",
	"msevents.js",
	"gesture.js",
	"ScrollMath.js",
	"ScrollStrategy.js",
	"Thumb.css",
	"Thumb.js",
	"TouchScrollStrategy.js",
	"TranslateScrollStrategy.js",
	"TransitionScrollStrategy.js",
	"Scroller.js",
	"Scroller.css"
);
