enyo.depends(
	"Toolbar.js",
	"ToolButton.js",
	"ToolButton2.js",
	"ToolInput.js",
	"ToolButtonGroup.js",
	"GroupedToolButton.js",
	"RadioToolButtonGroup.js",
	"RadioToolButton.js",
	"ToolInputBox.js",
	"ToolSearchInput.js"
);