enyo.depends(
	"langTest.js",
	//"LoaderTest.js",
	"KindTest.js",
	"JsonTest.js",
	"AsyncTest.js",
	"AjaxTest.js",
	"ComponentTest.js",
	"ComponentDispatchTest.js",
	"ComponentHandlersTest.js",
	"ControlTest.js",
	"ControlPropsTest.js",
	"DecodePackagePathTest.js",
	"PathResolverTest.js",
	"ViewportPositioningTest.js"
);
