enyo.depends(
	"readyTest.js",
	"langTest.js",
	// Disabling these job-related tests due to issues with rAF support and timing in PhantomJS.
	// "JobTest.js",
	// "JobsTest.js",
	// "ComponentJobTest.js",
	// "AnimatorTest.js",
	"LoaderTest.js",
	"KindTest.js",
	"ApplicationTest.js",
	"ComponentTest.js",
	"ComponentDispatchTest.js",
	"ComponentHandlersTest.js",
	"ControlTest.js",
	"DecodePackagePathTest.js",
	"PathResolverTest.js",
	"ViewportPositioningTest.js",
	"InheritanceSanityTest.js",
	"MultipleDispatchTest.js",
	"JsonTest.js",
	"AsyncTest.js",
	"AjaxTest.js",
	"ControllerTest.js",
	"ViewController.js"
);
