enyo.depends(
	"MixinSupport.js",
	"ComputedProperty.js",
	"ObserverMethod.js",
	"BindingSupport.js",
	"ApplicationSupport.js",
	"AutoBindingSupport.js",
	"ControllerSupport.js",
	"ModelSupport.js",
	"MultipleDispatchSupport.js"
);
