enyo.depends(
	"MixinSupport.js",
	"ComputedSupport.js",
	"ObserverSupport.js",
	"BindingSupport.js",
	"ApplicationSupport.js",
	"AutoBindingSupport.js",
	"ControllerSupport.js",
	"ModelSupport.js",
	"MultipleDispatchSupport.js"
);
