enyo.depends(
    "MixinSupport.js",
    "ComputedPropertySupport.js",
    "ObserverMethodSupport.js",
    "ApplicationSupport.js",
    "AutoBindingSupport.js",
    "ControllerSupport.js",
    "MultipleDispatchSupport.js"
);